### ISSUE TITLE
Internal error when creating pdf ticket

### ISSUE THREAD

**Issue by kial1** [imedias/glados#111]
This appears when I would like to download a pdf ticket:

![grafik](https://user-images.githubusercontent.com/64723035/111025917-a262cc80-83e7-11eb-8111-b417c958c393.png)

What can I do?

**Comment by kial1** [comment]
Also at http://raspberrypi/glados/index.php/ticket/12
![grafik](https://user-images.githubusercontent.com/64723035/111026601-52860480-83eb-11eb-82ff-3c7bb4a4d605.png)

**Comment by kial1** [comment]
Maybe this could also help: 
![grafik](https://user-images.githubusercontent.com/64723035/111026675-caecc580-83eb-11eb-9f5a-8246f613cfa7.png)

**Comment by chaoos** [comment]
Hi kial1

This is a bug in version 1.0.8. The reason is that the Barcode is only capable of uppercase letters and numbers. You can go to System->Settings and change the "Token characters" to numbers and uppercase (for example 0123456789ABCDEF). Now the PDF should work in newly created tickets. Old tickets with lowercase letter have to be removed and created again.

Regards
Roman
