### ISSUE TITLE
Screenshots not taken

### ISSUE THREAD

**Issue by sm8ps** [imedias/glados#67]
Using Prüfungsstick based on Lernstick version 2019-06-10, no screenshots are taken although the respective setting is two minutes in the Glados web-interface.

**Comment by chaoos** [comment]
This has been changed in the new Lernstick and is not yet adapted to Glados.

**Comment by sm8ps** [comment]
Do you think this is going to be adapted back into Lernstick? I think this is one the most important pieces when it comes to deal with possible cheating on an exam.

**Comment by chaoos** [comment]
It IS still in the Lernstick, its just that the directory to store the screenshots has been changed in the sense that it can be configured now (I don't remember the name of the config options right now). If nothing is configured (but screenshot enabled) the screenshots will be in `/.Screenshots`, and this is not in the user home directory anymore, which is backed up by glados.

**Comment by sm8ps** [comment]
OK, I see. So Glados will backup the screenshots separately from the specified backup path, right?

**Comment by chaoos** [comment]
No, the screenshots are produced from Lernstick itself, with the same mechanism. It's just that the path is not fixed anymore and the directory has another name. So Glados does not know where they are, and even whether they are backed up or not (they need to be in the backup path for this, see https://github.com/imedias/glados/blob/master/howtos/remote-backup-path.md).

**Comment by sm8ps** [comment]
Thanks for the explanation! The way you state it makes sense. No need for the bug label from my point of view.

One thing I would like to bring up: as said, screenshots are important in fighting against cheating as they are hard to fake. From that point of view it would make sense to have them outside of the user's home directory and without the user's permission to delete them. That seems to call for a separate location and thus a separate/additional backup procedure, doesn't it?

**Comment by chaoos** [comment]
No, the directory was already only readable by root, the user had no access to it. The only thing was that the directory being visible in the user home directory although not accessible, was misleading/confusing for the user. That's why it became a dotted directory, and the teacher has the possibility to place it wherever desired. For Glados it still needs to be in the backup path - the user home directory. When setting up the client system for the exam, Glados needs to configure the new screenshot mechanism correctly, such that they end up in the path being backed up. However, this will be in 1.0.6, you don't have to worry about that. I hope you can work without screenshots until then.

A workaround in the meantime could be, to use a squashfs filesystem and configure:
* In `/etc/lernstickWelcome` set `BackupSource=/home/user/`
* Create a soft link in the users home directory `ln -s .Screenshots Screenshots`

**Comment by sm8ps** [comment]
Great, thanks! I realize that I still not seeing the exact dividing lines between Lernstick, Prüfungsstick and Glados...

BTW, I did not mean to close it with my last post but my case is closed now.
