### ISSUE TITLE
Show absolute numbers in diagram

### ISSUE THREAD

**Issue by sm8ps** [imedias/glados#96]
When checking how many tickets are in what state, it would be more helpful to know the absolute numbers instead of the percentages which can be estimated from the pie diagram.

**Comment by chaoos** [comment]
Hi Stefan

I initially planned to drop the diagram anyways in one of the future versions, because currently I don't see any additional value in it. In the "general" tab under "related tickets" there are absolute numbers, that indeed are more meaningful that percentages.

But, since it's a very small change, I implemented it in the next version, 1.0.8 (see the commit https://github.com/imedias/glados/commit/78bb1ea79e6f117f7937b9b43cbd170a60f7e019).

Kind regards
Roman

**Comment by sm8ps** [comment]
Thanks, Roman! I agree that the diagram can be removed in the future.
